#!/bin/bash
set -euo pipefail

# Config from environment (all overridable via docker-compose env / .env file).
DB_HOST="${DB_HOST:-db}"
DB_PORT="${DB_PORT:-3306}"
DB_NAME="${DB_NAME:-throttle}"
DB_USER="${DB_USER:-throttle}"
DB_PASSWORD="${DB_PASSWORD:-throttle}"
THROTTLE_HOSTNAME="${THROTTLE_HOSTNAME:-localhost}"
THROTTLE_DEBUG="${THROTTLE_DEBUG:-false}"
THROTTLE_FORCE_CONFIG="${THROTTLE_FORCE_CONFIG:-1}"
THROTTLE_ADMINS="${THROTTLE_ADMINS:-}"
REDIS_HOST_CFG="${REDIS_HOST:-redis}"

export REDIS_HOST="${REDIS_HOST_CFG}"

APP_ROOT="/var/www/throttle"

# 1. Generate app/config.php from env (keeps secrets out of the image).
if [ ! -f "$APP_ROOT/app/config.php" ] || [ "$THROTTLE_FORCE_CONFIG" = "1" ]; then
	echo "Generating app/config.php (host=$THROTTLE_HOSTNAME db=$DB_HOST/$DB_NAME)..."
	DEBUG_PHP="false"
	if [ "$THROTTLE_DEBUG" = "1" ] || [ "$THROTTLE_DEBUG" = "true" ]; then
		DEBUG_PHP="true"
	fi
	# Admin Steam ID64s (comma-separated) -> PHP array literal.
	ADMINS_PHP=""
	if [ -n "$THROTTLE_ADMINS" ]; then
		for id in ${THROTTLE_ADMINS//,/ }; do
			[ -n "$id" ] && ADMINS_PHP="${ADMINS_PHP}'${id}', "
		done
		ADMINS_PHP="${ADMINS_PHP%, }"
	fi
	cat >"$APP_ROOT/app/config.php" <<PHP
<?php
// Generated by docker-entrypoint from environment. Do not edit by hand;
// change docker-compose env / .env instead.
return array(
    'debug' => $DEBUG_PHP,
    'maintenance' => false,
    'show-version' => true,

    'email-errors' => false,
    'email-errors.from' => 'noreply@example.com',
    'email-errors.to' => array(
        'webmaster@example.com',
    ),

    'db.host' => '${DB_HOST}',
    'db.user' => '${DB_USER}',
    'db.password' => '${DB_PASSWORD}',
    'db.name' => '${DB_NAME}',

    'hostname' => '${THROTTLE_HOSTNAME}',
    // Caddy reverse-proxy lives in the docker networks below.
    'trusted-proxies' => array('10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16'),

    'admins' => array(${ADMINS_PHP}),
    'developers' => array(),

    'apikey' => false,
    'accelerator' => false,

    'symbol-stores' => array(),
);
PHP
fi

# 2. Writable dirs (survives named-volume mounts as root).
mkdir -p "$APP_ROOT/logs" "$APP_ROOT/cache/profiler" "$APP_ROOT/cache/symbols" \
	"$APP_ROOT/dumps" "$APP_ROOT/symbols/public"
chmod -R a+w "$APP_ROOT/logs" "$APP_ROOT/cache" "$APP_ROOT/dumps" "$APP_ROOT/symbols" || true
chown -R www-data:www-data "$APP_ROOT/logs" "$APP_ROOT/cache" "$APP_ROOT/dumps" "$APP_ROOT/symbols" || true

# 3. Wait for MySQL (PHP/PDO so no mysql-client is needed in the image).
echo "Waiting for MySQL at ${DB_HOST}:${DB_PORT}..."
for i in $(seq 1 60); do
	if php -r '$c = @new PDO("mysql:host=".getenv("DB_HOST").";port=".getenv("DB_PORT"), getenv("DB_USER"), getenv("DB_PASSWORD")); exit($c ? 0 : 1);' 2>/dev/null; then
		echo "MySQL is up."
		break
	fi
	if [ "$i" -eq 60 ]; then
		echo "MySQL never became ready, continuing anyway (migrations may fail)."
	fi
	sleep 2
done

# 4. Vendor sanity (bind-mounted source trees may hide vendor/).
if [ ! -f "$APP_ROOT/vendor/autoload.php" ]; then
	echo "vendor/ missing, running composer install..."
	composer install --no-dev --no-progress --prefer-dist --no-interaction --working-dir="$APP_ROOT" ||
		composer install --no-dev --no-progress --prefer-dist --no-interaction --ignore-platform-reqs --working-dir="$APP_ROOT"
fi

# 5. Run migrations (matches README: php app/console.php migrations:migrate).
echo "Running migrations..."
php "$APP_ROOT/app/console.php" migrations:migrate --no-interaction || {
	echo "WARNING: migrations failed (first start against an empty DB can need a retry)."
}

rm -rf "$APP_ROOT/cache/"*.php "$APP_ROOT/cache/"*.twig 2>/dev/null || true

echo "Starting Apache..."
exec "$@"
